/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ActionEvents;
import Model.Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author JUAN JOSE MONSALVE
 */
public class ViewEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form ViewEmpleado
     */
    public ViewEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        botonGuardar1 = new javax.swing.JButton();
        buttonGroup4 = new javax.swing.ButtonGroup();
        botonGuardar4 = new javax.swing.JButton();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldIdEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldIdBodega = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldEdad = new javax.swing.JTextField();
        botonBorrarRegistro = new javax.swing.JButton();
        jCheckIdBodega = new javax.swing.JCheckBox();
        jCheckNombre = new javax.swing.JCheckBox();
        JcheckIdEmpleado = new javax.swing.JCheckBox();
        jCheckEdad = new javax.swing.JCheckBox();
        botonBorrar = new javax.swing.JButton();
        botonGuardar2 = new javax.swing.JButton();
        botonGuardar3 = new javax.swing.JButton();
        botonConsultar = new javax.swing.JButton();
        jCheckBoxUpdateNombre = new javax.swing.JCheckBox();
        jCheckBoxUpdateEdad = new javax.swing.JCheckBox();
        checkIdEmpleadoBorrar = new javax.swing.JCheckBox();

        botonGuardar1.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar1.setText("Insertar");
        botonGuardar1.setName("BotonGuardar"); // NOI18N
        botonGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardar1botonInsertar(evt);
            }
        });

        botonGuardar4.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar4.setText("Actualizar");
        botonGuardar4.setName("BotonGuardar"); // NOI18N
        botonGuardar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardar4botonInsertar(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Te Reto A Programarlo S.A.S");

        jPanel1.setBackground(new java.awt.Color(119, 200, 180));
        jPanel1.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(119, 200, 180));
        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edad:");
        jLabel1.setName("Label1"); // NOI18N
        jLabel1.setOpaque(true);

        fieldNombre.setName("field1"); // NOI18N

        jLabel2.setBackground(new java.awt.Color(119, 200, 180));
        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IdBodega:");
        jLabel2.setName("Label1"); // NOI18N
        jLabel2.setOpaque(true);

        fieldIdEmpleado.setName("field1"); // NOI18N

        jLabel3.setBackground(new java.awt.Color(119, 200, 180));
        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre:");
        jLabel3.setName("Label1"); // NOI18N
        jLabel3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingreso de Registros");

        fieldIdBodega.setName("field1"); // NOI18N
        fieldIdBodega.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(119, 200, 180));
        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("IdEmpleado:");
        jLabel5.setName("Label1"); // NOI18N
        jLabel5.setOpaque(true);

        fieldEdad.setName("field1"); // NOI18N

        botonBorrarRegistro.setBackground(new java.awt.Color(255, 255, 255));
        botonBorrarRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrarRegistro.setText("Borrar Registro");
        botonBorrarRegistro.setName("BotonGuardar"); // NOI18N
        botonBorrarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarRegistro(evt);
            }
        });

        jCheckIdBodega.setBackground(new java.awt.Color(119, 200, 180));
        jCheckIdBodega.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckIdBodega.setText("IdBodega");
        jCheckIdBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckIdBodegaActionPerformed(evt);
            }
        });

        jCheckNombre.setBackground(new java.awt.Color(119, 200, 180));
        jCheckNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckNombre.setText("Nombre");
        jCheckNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckNombreActionPerformed(evt);
            }
        });

        JcheckIdEmpleado.setBackground(new java.awt.Color(119, 200, 180));
        JcheckIdEmpleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcheckIdEmpleado.setText("IdEmpleado");
        JcheckIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcheckIdEmpleadoActionPerformed(evt);
            }
        });

        jCheckEdad.setBackground(new java.awt.Color(119, 200, 180));
        jCheckEdad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckEdad.setText("Edad");
        jCheckEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckEdadActionPerformed(evt);
            }
        });

        botonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        botonBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonBorrar.setText("Borrar Datos");
        botonBorrar.setName("BotonSalir"); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrar(evt);
            }
        });

        botonGuardar2.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar2.setText("Insertar");
        botonGuardar2.setName("BotonGuardar"); // NOI18N
        botonGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertar(evt);
            }
        });

        botonGuardar3.setBackground(new java.awt.Color(255, 255, 255));
        botonGuardar3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonGuardar3.setText("Actualizar");
        botonGuardar3.setName("BotonGuardar"); // NOI18N
        botonGuardar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUpdate(evt);
            }
        });

        botonConsultar.setBackground(new java.awt.Color(255, 255, 255));
        botonConsultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botonConsultar.setText("Consultar por:");
        botonConsultar.setName("BotonGuardar"); // NOI18N
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultar(evt);
            }
        });

        jCheckBoxUpdateNombre.setBackground(new java.awt.Color(119, 200, 180));
        jCheckBoxUpdateNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxUpdateNombre.setText("Nombre");
        jCheckBoxUpdateNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckNombreUpdateActionPerformed(evt);
            }
        });

        jCheckBoxUpdateEdad.setBackground(new java.awt.Color(119, 200, 180));
        jCheckBoxUpdateEdad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jCheckBoxUpdateEdad.setText("Edad");
        jCheckBoxUpdateEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckEdadUpdateActionPerformed(evt);
            }
        });

        checkIdEmpleadoBorrar.setBackground(new java.awt.Color(119, 200, 180));
        checkIdEmpleadoBorrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkIdEmpleadoBorrar.setText("IdEmpleado");
        checkIdEmpleadoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBorrarIdEmpleado(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldIdEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(fieldEdad)
                                .addComponent(fieldIdBodega))
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcheckIdEmpleado)
                            .addComponent(jCheckNombre))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckIdBodega)
                            .addComponent(jCheckEdad)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jCheckBoxUpdateNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBoxUpdateEdad))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkIdEmpleadoBorrar)
                                    .addComponent(botonBorrarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonGuardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIdBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(botonBorrarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(checkIdEmpleadoBorrar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(botonGuardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBoxUpdateNombre)
                            .addComponent(jCheckBoxUpdateEdad))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(botonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckIdBodega, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JcheckIdEmpleado, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckNombre)
                            .addComponent(jCheckEdad)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarRegistro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarRegistro
        // Borrar el registro por la Id del Empleado
        if (checkIdEmpleadoBorrar.isSelected()) {
            String idEmpleado = fieldIdEmpleado.getText().trim();
            if (!"".equals(idEmpleado)){
                ActionEvents.deleteEmpleado(idEmpleado);
            }else{
                JOptionPane.showMessageDialog(null, "Ingresa la Id del Empleado a Borrar");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar el ítem IdEmpleado\npara Borrar el registro.");
        }
        
    }//GEN-LAST:event_botonBorrarRegistro

    private void botonBorrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrar
        /*  Esta funcion Borra el texto en los campos de texto de
        de la parte superior.
        */
        fieldEdad.setText("");
        fieldIdBodega.setText("");
        fieldIdEmpleado.setText("");
        fieldNombre.setText("");
        
    }//GEN-LAST:event_botonBorrar

    private void botonGuardar1botonInsertar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardar1botonInsertar
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardar1botonInsertar

    private void botonInsertar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertar
        // TODO add your handling code here:
        // mirar condicion de que las id sean numeros
        String nombre = fieldNombre.getText().trim();        
        String edad = fieldEdad.getText().trim();
        String idBodega = fieldIdBodega.getText().trim();
        String idEmpleado = fieldIdEmpleado.getText().trim();       
        if (( !"".equals(nombre) && !"".equals(edad)) &&
            !"".equals(idBodega) && !"".equals(idEmpleado)){
        
            /* Creacion del Objeto Alumno*/
            ActionEvents.insertarEmpleado(
            new Empleado(Integer.valueOf(idBodega), Integer.valueOf(idEmpleado), nombre, Integer.valueOf(edad))
            );     
            System.out.println("here");
        }else{
            JOptionPane.showMessageDialog(null, "Ingresa todos los campos correctamente");
        }
    }//GEN-LAST:event_botonInsertar

    private void botonUpdate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUpdate
        // TODO add your handling code here:
        if (jCheckBoxUpdateEdad.isSelected() || jCheckBoxUpdateNombre.isSelected()) {
            
            // Chequeo de que el campo IdEmpleado no es vacio
            if (!"".equals(fieldIdEmpleado.getText())){
                
                // Valor del campo nombre y edad deacuerdo al checkbox seleccionado
                String edad = (jCheckBoxUpdateEdad.isSelected()) ? fieldEdad.getText().trim(): "";
                String nombre = (jCheckBoxUpdateNombre.isSelected()) ? fieldNombre.getText().trim(): "";
//                System.out.println("edad:"+edad + "nombre:"+nombre);
                
                if (!"".equals(nombre) || !"".equals(edad)){
                    int idEmpleado = Integer.valueOf(fieldIdEmpleado.getText().trim());            
                    ActionEvents.updateEmpleado(idEmpleado,nombre, edad);
                }else{
                    JOptionPane.showMessageDialog(null, "Ingresa los datos completos: \n\n *IdEmpleado \n *Nombre ó Edad");
                } 
            }else{
                JOptionPane.showMessageDialog(null, "No has ingresado la Id del Empleado");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona un ítem de Actualización \n\n *Nombre y/ó Edad");
        }
        
        
    }//GEN-LAST:event_botonUpdate

    private void botonGuardar4botonInsertar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardar4botonInsertar
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardar4botonInsertar

    private void botonConsultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultar
        // TODO add your handling code here:
        String idBodega = "";
        String idEmpleado = "";
        String nombre = "";
        String edad = "";
        String MessageError = "";
        if (jCheckIdBodega.isSelected()) {
            if (!"".equals(fieldIdBodega.getText())) {
                idBodega = fieldIdBodega.getText().trim();
            }else{
                MessageError += "\nIngresa algún valor\nen el campo *IdBodega";
            }            
        }
        if (JcheckIdEmpleado.isSelected()) {
            if (!"".equals(fieldIdEmpleado.getText())) {
                idEmpleado = fieldIdEmpleado.getText().trim();
            }else{
                MessageError += "\nIngresa algún valor\nen el campo *IdEmpleado";
            }            
        }
        if (jCheckNombre.isSelected()) {
            if (!"".equals(fieldNombre.getText())) {
                nombre = fieldNombre.getText().trim();
            }else{
                MessageError += "\nIngresa algún valor\nen el campo *nombre";
            }            
        }
        if (jCheckEdad.isSelected()) {
            if (!"".equals(fieldEdad.getText())) {
                edad = fieldEdad.getText().trim();
            }else{
                MessageError += "\nIngresa algún valor\nen el campo *nombre";
            }            
        }
        if ("".equals(MessageError)) {
            // Llamado final al controlador
            ActionEvents.ConsultaEmpleado(idBodega, idEmpleado, nombre, edad);
        }else{
            JOptionPane.showMessageDialog(null, "Error"+MessageError);
        }
    }//GEN-LAST:event_botonConsultar

    private void JcheckIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcheckIdEmpleadoActionPerformed
        // Asignacion del estado de los campos segun el check selecionado

        fieldNombre.setEnabled((jCheckNombre.isSelected()));
        fieldEdad.setEnabled((jCheckEdad.isSelected()));
        fieldIdBodega.setEnabled((jCheckIdBodega.isSelected()));
        fieldIdEmpleado.setEnabled((JcheckIdEmpleado.isSelected())); 
    }//GEN-LAST:event_JcheckIdEmpleadoActionPerformed

    private void jCheckIdBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckIdBodegaActionPerformed
        // Asignacion del estado de los campos segun el check selecionado

        fieldNombre.setEnabled((jCheckNombre.isSelected()));
        fieldEdad.setEnabled((jCheckEdad.isSelected()));
        fieldIdBodega.setEnabled((jCheckIdBodega.isSelected()));
        fieldIdEmpleado.setEnabled((JcheckIdEmpleado.isSelected())); 
    }//GEN-LAST:event_jCheckIdBodegaActionPerformed

    private void jCheckEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckEdadActionPerformed
        // Asignacion del estado de los campos segun el check selecionado

        fieldNombre.setEnabled((jCheckNombre.isSelected()));
        fieldEdad.setEnabled((jCheckEdad.isSelected()));
        fieldIdBodega.setEnabled((jCheckIdBodega.isSelected()));
        fieldIdEmpleado.setEnabled((JcheckIdEmpleado.isSelected())); 
    }//GEN-LAST:event_jCheckEdadActionPerformed

    private void jCheckNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckNombreActionPerformed
        // Asignacion del estado de los campos segun el check selecionado
        fieldNombre.setEnabled((jCheckNombre.isSelected()));
        fieldEdad.setEnabled((jCheckEdad.isSelected()));
        fieldIdBodega.setEnabled((jCheckIdBodega.isSelected()));
        fieldIdEmpleado.setEnabled((JcheckIdEmpleado.isSelected())); 
    }//GEN-LAST:event_jCheckNombreActionPerformed

    private void jCheckNombreUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckNombreUpdateActionPerformed
        // TODO add your handling code here:

        if (jCheckBoxUpdateNombre.isSelected()) {
            OnCheckInUpdate();
            fieldIdEmpleado.setEnabled(true);
            fieldIdBodega.setEnabled(false);
            if (!jCheckBoxUpdateEdad.isSelected()) {
                fieldEdad.setEnabled(false);
            }else{
                fieldNombre.setEnabled(true);
                fieldEdad.setEnabled(true);
            }
        }else{
            if (!jCheckBoxUpdateEdad.isSelected()) {
                OffCheckInUpdate();
                fieldIdBodega.setEnabled(true);
                fieldNombre.setEnabled(true);
                fieldEdad.setEnabled(true);
                fieldIdEmpleado.setEnabled(true);
            }else{
                fieldNombre.setEnabled(false);
                fieldEdad.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jCheckNombreUpdateActionPerformed

    private void jCheckEdadUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckEdadUpdateActionPerformed
        // TODO add your handling code here:

        if (jCheckBoxUpdateEdad.isSelected()) {
            OnCheckInUpdate();
            fieldIdEmpleado.setEnabled(true);
            fieldIdBodega.setEnabled(false);
            if (!jCheckBoxUpdateNombre.isSelected()) {
                fieldNombre.setEnabled(false);
                fieldEdad.setEnabled(true);
            }else{
                fieldEdad.setEnabled(true);
                fieldNombre.setEnabled(true);
            }
        }else{
            if (!jCheckBoxUpdateNombre.isSelected()) {
                OffCheckInUpdate();
                fieldIdBodega.setEnabled(true);
                fieldNombre.setEnabled(true);
                fieldEdad.setEnabled(true);
                fieldIdEmpleado.setEnabled(true);
            }else{
                fieldEdad.setEnabled(false);
                fieldNombre.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jCheckEdadUpdateActionPerformed

    private void checkBorrarIdEmpleado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBorrarIdEmpleado
        // TODO add your handling code here:
        // si o si el IdEmpleado debe estar disponible al seleccionar o no el check
        fieldIdEmpleado.setEnabled(true);
        if (checkIdEmpleadoBorrar.isSelected()) {
            OnCheckInDelete();
        }else{
            OffCheckInDelete();
        }
    }//GEN-LAST:event_checkBorrarIdEmpleado

    private void OnCheckInUpdate(){
        // desabilitar los otros checks
        JcheckIdEmpleado.setEnabled(false);
        jCheckIdBodega.setEnabled(false);
        jCheckEdad.setEnabled(false);
        jCheckNombre.setEnabled(false);
        checkIdEmpleadoBorrar.setEnabled(false);        
    }
    
    private void OffCheckInUpdate(){
        // habilitar los otros checks
        JcheckIdEmpleado.setEnabled(true);
        jCheckIdBodega.setEnabled(true);
        jCheckBoxUpdateEdad.setEnabled(true);
        jCheckBoxUpdateNombre.setEnabled(true);
        jCheckEdad.setEnabled(true);
        jCheckNombre.setEnabled(true);
        checkIdEmpleadoBorrar.setEnabled(true);
    }
    
    private void OnCheckInDelete(){
        // cheks In Delete
        JcheckIdEmpleado.setEnabled(false);
        jCheckIdBodega.setEnabled(false);
        jCheckBoxUpdateEdad.setEnabled(false);
        jCheckBoxUpdateNombre.setEnabled(false);
        jCheckEdad.setEnabled(false);
        jCheckNombre.setEnabled(false);
        fieldEdad.setEnabled(false);
        fieldIdBodega.setEnabled(false);
        fieldNombre.setEnabled(false);
    }
    
    private void OffCheckInDelete(){
        JcheckIdEmpleado.setEnabled(true);
        jCheckIdBodega.setEnabled(true);
        jCheckBoxUpdateEdad.setEnabled(true);
        jCheckBoxUpdateNombre.setEnabled(true);
        jCheckEdad.setEnabled(true);
        jCheckNombre.setEnabled(true);
        fieldEdad.setEnabled(true);
        fieldIdBodega.setEnabled(true);
        fieldNombre.setEnabled(true);    
    
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewEmpleado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JcheckIdEmpleado;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrarRegistro;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonGuardar1;
    private javax.swing.JButton botonGuardar2;
    private javax.swing.JButton botonGuardar3;
    private javax.swing.JButton botonGuardar4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox checkIdEmpleadoBorrar;
    private javax.swing.JTextField fieldEdad;
    private javax.swing.JTextField fieldIdBodega;
    private javax.swing.JTextField fieldIdEmpleado;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JCheckBox jCheckBoxUpdateEdad;
    private javax.swing.JCheckBox jCheckBoxUpdateNombre;
    private javax.swing.JCheckBox jCheckEdad;
    private javax.swing.JCheckBox jCheckIdBodega;
    private javax.swing.JCheckBox jCheckNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
